import { fmt } from './notify';
import type { XSettings } from './types';
import { appShell, esc, safeUrl } from './ui';

 type Row = Record<string, string | number>;

function num(v: unknown): number { return Number(v) || 0; }
function time(ts: unknown): string { const n = num(ts); return n ? `<time data-ts="${n}">${new Date(n).toISOString()}</time>` : '—'; }
function delta(v: unknown): string {
  const n = num(v);
  if (!n) return '<span class="muted">—</span>';
  return `<span class="${n > 0 ? 'delta-up' : 'delta-down'}">${n > 0 ? '+' : ''}${esc(n.toFixed(1))}%</span>`;
}

export function renderOverview(data: {
  settings: XSettings;
  trends: Row[];
  rules: Row[];
  posts: Row[];
  alerts: Row[];
  runs: Row[];
  xConfigured: boolean;
  tgConfigured: boolean;
}): string {
  const { settings, trends, rules, posts, alerts, runs, xConfigured, tgConfigured } = data;
  const latestRun = runs[0];
  const latestErrors = String(latestRun?.errors ?? '').trim();
  const enabledRules = rules.filter((r) => !!num(r.enabled)).length;
  const topTrend = trends[0];
  const strongest = rules.filter((r) => num(r.ratio_5m) > 0).sort((a,b) => num(b.ratio_5m)-num(a.ratio_5m))[0];
  const state = !xConfigured ? ['bad','缺少 X API Token'] : latestErrors ? ['warn','最近一轮有错误'] : latestRun ? ['ok','运行正常'] : ['idle','等待首次采集'];

  const trendRows = trends.slice(0,8).map((t) => `<tr><td class="rank">#${esc(t.rank)}</td><td class="title-cell"><a class="link" href="https://x.com/search?q=${encodeURIComponent(String(t.trend_name))}&src=typed_query&f=live" target="_blank" rel="noopener">${esc(t.trend_name)} ↗</a></td><td class="num strong">${esc(fmt(num(t.tweet_count)))}</td><td class="num">${delta(t.delta_pct)}</td></tr>`).join('');
  const spikeRows = rules.filter((r) => num(r.enabled)).slice(0,6).map((r) => `<tr><td><span class="badge ${String(r.type)==='account'?'info':'hot'}">${String(r.type)==='account'?'账号':'热词'}</span></td><td class="title-cell"><span class="strong">${esc(r.label)}</span><div class="muted" style="font-size:11px">${esc(r.query)}</div></td><td class="num strong">${esc(fmt(num(r.count_5m)))}</td><td class="num"><span class="${num(r.ratio_5m)>=settings.spikeRatio?'delta-up':'muted'}">${num(r.ratio_5m)?esc(num(r.ratio_5m).toFixed(1))+'×':'—'}</span></td></tr>`).join('');
  const postCards = posts.slice(0,4).map((p) => `<article class="post"><div class="post-head"><div><span class="author">${esc(p.author_name || p.username)}</span> <span class="handle">@${esc(p.username)}</span></div><span class="badge info">互动 ${esc(fmt(num(p.engagement)))}</span></div><div class="post-text">${esc(String(p.text||'').slice(0,280))}</div><div class="post-metrics"><span>♡ ${esc(fmt(num(p.like_count)))}</span><span>↻ ${esc(fmt(num(p.repost_count)))}</span><span>💬 ${esc(fmt(num(p.reply_count)))}</span><span>👁 ${esc(fmt(num(p.impression_count)))}</span></div><div class="post-actions"><a class="btn small" href="${esc(safeUrl(p.url))}" target="_blank" rel="noopener">在 X 查看 ↗</a></div></article>`).join('');

  const body = `<section class="hero"><div class="hero-copy"><div class="eyebrow">X-only intelligence</div><h1>只盯 X：热词、热度、暴涨和热门帖子。</h1><p>不再跳多个平台。X 官方 Trends 负责发现热点，你添加的关键词/账号规则负责计算 5 分钟、15 分钟、1 小时热度和异常增速。</p></div><div class="hero-actions"><a class="btn accent" href="/admin#run">▶ 立即采集</a><a class="btn" href="/watch">＋ 添加监控</a><a class="btn" href="/trends">查看 X 热榜</a></div></section>
<div class="stat-grid grid"><div class="stat"><div class="label">当前 #1 趋势</div><div class="value" style="font-size:20px">${esc(topTrend?.trend_name ?? '—')}</div><div class="meta">${topTrend ? fmt(num(topTrend.tweet_count))+' 条量级' : '等待采集'}</div></div><div class="stat"><div class="label">启用监控</div><div class="value">${enabledRules}</div><div class="meta">关键词 + 账号</div></div><div class="stat"><div class="label">最强 5 分钟增速</div><div class="value">${strongest ? esc(num(strongest.ratio_5m).toFixed(1))+'×' : '—'}</div><div class="meta">${esc(strongest?.label ?? '暂无监控数据')}</div></div><div class="stat"><div class="label">自动采集</div><div class="value" style="font-size:22px">${settings.enabled ? '每 '+settings.intervalMinutes+' 分钟' : '已暂停'}</div><div class="meta">下次：${settings.nextRunAt ? time(settings.nextRunAt) : '—'}</div></div></div>
<div class="split"><section class="panel"><div class="panel-head"><div class="panel-title">🔥 X 实时热榜</div><a class="btn small" href="/trends">完整热榜</a></div>${trendRows?`<div class="table-wrap"><table class="table"><thead><tr><th>排名</th><th>趋势</th><th class="num">帖子量</th><th class="num">较上轮</th></tr></thead><tbody>${trendRows}</tbody></table></div>`:`<div class="empty"><div class="icon">𝕏</div><strong>还没有 X Trends 数据</strong><div>${xConfigured?'去设置点一次立即采集。':'先在 Cloudflare 添加 X_BEARER_TOKEN。'}</div><a class="btn primary" href="/admin">打开设置</a></div>`}</section><div class="stack"><section class="panel"><div class="panel-head"><div class="panel-title">运行状态</div><span class="pill ${state[0]}">${state[1]}</span></div><div class="panel-body"><div class="metric-grid"><div class="metric"><div class="k">最近 Trends</div><div class="v">${esc(latestRun?.trends ?? 0)}</div></div><div class="metric"><div class="k">规则</div><div class="v">${esc(latestRun?.rules ?? 0)}</div></div><div class="metric"><div class="k">帖子</div><div class="v">${esc(latestRun?.posts ?? 0)}</div></div><div class="metric"><div class="k">Telegram</div><div class="v" style="font-size:15px">${tgConfigured?'已连接':'未配置'}</div></div></div>${latestErrors?`<div class="notice warn" style="margin-top:12px">${esc(latestErrors)}</div>`:''}</div><div class="panel-foot">最近运行：${time(latestRun?.ts)}</div></section><section class="panel"><div class="panel-head"><div class="panel-title">🚀 最近告警</div></div>${alerts.length?`<div class="panel-body">${alerts.slice(0,5).map(a=>`<div style="padding:8px 0;border-bottom:1px solid var(--line)"><div class="strong">${esc(a.label)}</div><div class="muted" style="font-size:11px">${esc(a.detail)} · ${time(a.ts)}</div></div>`).join('')}</div>`:`<div class="empty"><strong>暂无告警</strong><div>达到阈值后会显示在这里并推送 Telegram。</div></div>`}</section></div></div>
<div style="height:16px"></div><div class="two"><section class="panel"><div class="panel-head"><div class="panel-title">📈 监控规则热度</div><a class="btn small" href="/watch">管理规则</a></div>${spikeRows?`<div class="table-wrap"><table class="table"><thead><tr><th>类型</th><th>规则</th><th class="num">5分钟</th><th class="num">增速</th></tr></thead><tbody>${spikeRows}</tbody></table></div>`:`<div class="empty"><div class="icon">＋</div><strong>还没有监控规则</strong><div>添加关键词或 X 账号后，这里就会显示实时热度。</div><a class="btn accent" href="/watch">添加第一个监控</a></div>`}</section><section class="panel"><div class="panel-head"><div class="panel-title">💬 热门帖子</div><a class="btn small" href="/posts">查看更多</a></div><div class="panel-body">${postCards||'<div class="empty"><strong>暂无帖子</strong><div>添加监控规则并采集后自动出现。</div></div>'}</div></section></div>`;
  return appShell({title:'X Radar · 总览',active:'overview',body});
}

export function renderTrendsPage(trends: Row[], settings: XSettings): string {
  const rows = trends.map(t=>`<tr><td class="rank">#${esc(t.rank)}</td><td class="title-cell"><div class="strong">${esc(t.trend_name)}</div></td><td class="num strong">${esc(fmt(num(t.tweet_count)))}</td><td class="num">${delta(t.delta_pct)}</td><td class="num"><a class="btn small" href="https://x.com/search?q=${encodeURIComponent(String(t.trend_name))}&src=typed_query&f=live" target="_blank" rel="noopener">在 X 搜索 ↗</a></td></tr>`).join('');
  const body=`<section class="hero"><div class="hero-copy"><div class="eyebrow">Official X Trends</div><h1>X 官方实时热榜</h1><p>当前 WOEID：${esc(settings.woeid)}。帖子量来自 X Trends API；“较上轮”是我们自己的 D1 快照对比。</p></div><div class="hero-actions"><a class="btn accent" href="/admin#run">▶ 立即刷新</a><a class="btn" href="/admin#x-settings">地区与数量设置</a></div></section><section class="panel"><div class="panel-head"><div class="panel-title">实时趋势 <span class="muted" style="font-weight:500">Top ${esc(settings.maxTrends)}</span></div><span class="pill info">WOEID ${esc(settings.woeid)}</span></div>${rows?`<div class="table-wrap"><table class="table"><thead><tr><th>排名</th><th>趋势词</th><th class="num">帖子量</th><th class="num">较上轮</th><th class="num">操作</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="empty"><div class="icon">𝕏</div><strong>暂无趋势数据</strong><div>去设置页配置 X_BEARER_TOKEN 后点击立即采集。</div><a class="btn primary" href="/admin">打开设置</a></div>`}</section>`;
  return appShell({title:'X Radar · X 热榜',active:'trends',body});
}

export function renderWatchPage(rules: Row[], authed: boolean, settings: XSettings): string {
  const cards=rules.map(r=>`<div class="rule-card" data-rule="${esc(r.id)}"><div class="rule-top"><div><div class="rule-label">${esc(r.label)} <span class="badge ${String(r.type)==='account'?'info':'hot'}">${String(r.type)==='account'?'账号':'关键词'}</span></div><div class="rule-query">${esc(r.query)}</div></div><span class="pill ${num(r.enabled)?'ok':'idle'}">${num(r.enabled)?'监控中':'已暂停'}</span></div><div class="rule-metrics"><div><span>最近 5 分钟</span><b>${esc(fmt(num(r.count_5m)))}</b></div><div><span>前 5 分钟</span><b>${esc(fmt(num(r.previous_5m)))}</b></div><div><span>近 1 小时</span><b>${esc(fmt(num(r.count_60m)))}</b></div><div><span>5 分钟增速</span><b class="${num(r.ratio_5m)>=settings.spikeRatio?'delta-up':''}">${num(r.ratio_5m)?esc(num(r.ratio_5m).toFixed(1))+'×':'—'}</b></div></div>${authed?`<div class="form-row" style="margin-top:11px"><button class="btn small toggle" data-id="${esc(r.id)}" data-enabled="${num(r.enabled)?'0':'1'}">${num(r.enabled)?'暂停':'启用'}</button><button class="btn small danger delete" data-id="${esc(r.id)}">删除</button></div>`:''}</div>`).join('');
  const add=authed?`<section class="panel" id="add"><div class="panel-head"><div class="panel-title">＋ 新增监控</div></div><div class="panel-body"><div class="form-row"><div class="field"><label>类型</label><select id="ruleType"><option value="keyword">关键词 / 搜索规则</option><option value="account">X 账号</option></select></div><div class="field grow"><label>显示名称</label><input id="ruleLabel" placeholder="例如 OpenAI / Elon Musk"></div><div class="field grow"><label>关键词、X 查询语法或 @用户名</label><input id="ruleQuery" placeholder="例如 OpenAI lang:en 或 @elonmusk"></div><button id="addRule" class="btn accent">添加并启用</button></div><div class="notice" style="margin-top:12px">关键词支持 X Recent Search 查询语法；账号类型只需要填 @用户名。每轮会计算 5 分钟、15 分钟、1 小时帖子量，并抓热门帖子。</div><div id="ruleMsg" style="margin-top:10px"></div></div></section>`:`<div class="notice">你当前未登录管理会话。可以浏览热度，但要新增/暂停/删除规则，请先 <a class="link" href="/admin">登录设置页</a>。</div>`;
  const body=`<section class="hero"><div class="hero-copy"><div class="eyebrow">Watchlist</div><h1>关键词和账号，直接在页面监控。</h1><p>每条规则都显示最近 5 分钟、前 5 分钟、15 分钟和 1 小时帖子量；达到 ${esc(settings.spikeRatio)}× 且至少 ${esc(settings.spikeMinPosts)} 条时触发告警。</p></div><div class="hero-actions"><a class="btn accent" href="/admin#run">▶ 立即采集</a></div></section>${add}<div style="height:16px"></div><section class="panel"><div class="panel-head"><div class="panel-title">监控列表</div><span class="pill info">${rules.length} 条</span></div><div class="panel-body"><div class="grid">${cards||'<div class="empty"><div class="icon">＋</div><strong>还没有任何监控</strong><div>上面添加一个关键词或 X 账号即可开始。</div></div>'}</div></div></section>`;
  const script=authed?`(function(){var msg=document.getElementById('ruleMsg');function show(t,b){msg.className='notice '+(b?'bad':'');msg.textContent=t}async function api(path,opt){var r=await fetch(path,Object.assign({credentials:'same-origin'},opt||{}));var d=await r.json().catch(function(){return{}});if(!r.ok)throw new Error(d.error||'操作失败');return d}document.getElementById('addRule').onclick=async function(){try{var type=document.getElementById('ruleType').value,label=document.getElementById('ruleLabel').value.trim(),query=document.getElementById('ruleQuery').value.trim();await api('/api/rules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:type,label:label,query:query})});location.reload()}catch(e){show(e.message,true)}};document.querySelectorAll('.toggle').forEach(function(b){b.onclick=async function(){try{await api('/api/rules/'+b.dataset.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:b.dataset.enabled==='1'})});location.reload()}catch(e){show(e.message,true)}}});document.querySelectorAll('.delete').forEach(function(b){b.onclick=async function(){if(!confirm('确定删除这条监控规则？'))return;try{await api('/api/rules/'+b.dataset.id,{method:'DELETE'});location.reload()}catch(e){show(e.message,true)}}})})();`:'';
  return appShell({title:'X Radar · 监控规则',active:'watch',body,script});
}

export function renderPostsPage(posts: Row[]): string {
  const cards=posts.map(p=>`<article class="post"><div class="post-head"><div><span class="author">${esc(p.author_name||p.username)}</span> <span class="handle">@${esc(p.username)}</span>${num(p.verified)?' <span class="badge info">✓</span>':''}</div><span class="badge hot">互动 ${esc(fmt(num(p.engagement)))}</span></div><div class="post-text">${esc(p.text)}</div><div class="post-metrics"><span>♡ ${esc(fmt(num(p.like_count)))}</span><span>↻ ${esc(fmt(num(p.repost_count)))}</span><span>💬 ${esc(fmt(num(p.reply_count)))}</span><span>❞ ${esc(fmt(num(p.quote_count)))}</span><span>👁 ${esc(fmt(num(p.impression_count)))}</span><span>${time(p.fetched_at)}</span></div><div class="post-actions"><a class="btn small" href="${esc(safeUrl(p.url))}" target="_blank" rel="noopener">在 X 查看 ↗</a>${p.rule_labels?` <span class="muted" style="font-size:11px">来自监控：${esc(p.rule_labels)}</span>`:''}</div></article>`).join('');
  const body=`<section class="hero"><div class="hero-copy"><div class="eyebrow">Top Posts</div><h1>监控规则里正在升温的热门帖子。</h1><p>按点赞、转发、回复、引用等公开互动加权排序。点击“在 X 查看 ↗”才会离开本站。</p></div><div class="hero-actions"><a class="btn" href="/watch">管理监控规则</a><a class="btn accent" href="/admin#run">▶ 刷新</a></div></section><section class="panel"><div class="panel-head"><div class="panel-title">近 24 小时热门帖子</div><span class="pill info">${posts.length} 条</span></div><div class="panel-body"><div class="post-list">${cards||'<div class="empty"><div class="icon">💬</div><strong>暂时没有帖子数据</strong><div>先添加监控规则并执行一次采集。</div><a class="btn accent" href="/watch">添加监控</a></div>'}</div></div></section>`;
  return appShell({title:'X Radar · 热门帖子',active:'posts',body});
}
